
version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      target: build
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Production service
  app-prod:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod

  # Alternative development setup with hot reload
  app:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    profiles:
      - local
